[package]
name = "jstime"
version = "0.4.1"
authors = ["Myles Borins <myles.borins@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.8.1"
rustyline = "6.2.0"
