sign-commit	= true
sign-tag = true
disable-publish = true
pre-release-commit-message = "{{crate_name}} version {{version}}"
post-release-commit-message = "Working on {{crate_name}} version {{next_version}}"
