on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]
        
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: jstime
            archive_name: jstime-linux.tar.gz
            asset_name: jstime-linux.tar.gz
          - name: windows
            os: windows-latest
            artifact_name: jstime.exe
            archive_name: jstime-windows.zip
            asset_name: jstime-windows.zip
          - name: macos
            os: macos-latest
            artifact_name: jstime
            archive_name: jstime-macos.tar.gz
            asset_name: jstime-macos.tar.gz
    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: archive release
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          7z a "target/release/${{ matrix.archive_name }}" "target/release/${{ matrix.artifact_name }}"
        else
          tar czf "target/release/${{ matrix.archive_name }}" "target/release/${{ matrix.artifact_name }}"
        fi

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.archive_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  publish:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: This is an automated release
          draft: false
          prerelease: false
